name: Build & Publish to Root Pages Repo

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  shellcheck:
    name: ShellCheck 🛠
    runs-on: ubuntu-latest
    if: github.repository == 'NJUPT-NAVI/NJUPT-Survival-Guide'
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 🐚 Full ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          triggering-event: ${{ github.event_name }}
          strict-check-on-push: true
          base: ${{ github.event.before }}
          head: ${{ github.sha }}
          severity: error

  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs: [shellcheck]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Build (Astro)
        uses: withastro/action@v3
        with:
          node-version: 20

      - name: Make sync script executable
        run: chmod +x scripts/sync-dist.sh

      - name: Deploy
        env:
          DEPLOY_REPO_TOKEN: ${{ secrets.DEPLOY_REPO_TOKEN }}
        run: ./scripts/sync-dist.sh dist