name: Build & Publish to Root Pages Repo

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

# 全局最小权限（跨仓库推送用 PAT secret，自身只读即可）
permissions:
  contents: read

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  shellcheck:
    name: ShellCheck 🛠
    runs-on: ubuntu-latest
    # 仅在源码仓库运行（防护：若被 fork 改名）
    if: github.repository == 'NJUPT-NAVI/NJUPT-Survival-Guide'
    permissions:
      contents: read
      security-events: write   # 允许 Code Scanning 上传结果（该 action 会用到）
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 🐚 Full ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          triggering-event: ${{ github.event_name }}
          strict-check-on-push: true
          base: ${{ github.event.before }}
          head: ${{ github.sha }}
          severity: error

  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs: [shellcheck]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build (Astro)
        uses: withastro/action@v3
        with:
          node-version: 20

      - name: Checkout target (pages repo)
        uses: actions/checkout@v4
        with:
          repository: NJUPT-NAVI/njupt-navi.github.io
          token: ${{ secrets.DEPLOY_REPO_TOKEN }}
          path: target
          fetch-depth: 0

      - name: Make sync script executable
        run: chmod +x scripts/sync-dist.sh

      - name: Sync & publish
        run: ./scripts/sync-dist.sh dist target